### ISSUE TITLE
RuntimeError: mat1 and mat2 shapes cannot be multiplied (1440x128 and 130x64)

### ISSUE THREAD

**Issue by Abbsalehi** [FreeButUselessSoul/occ-nerf#2] opened 2023-09-08 12:08 UTC
I'm getting this error "RuntimeError: mat1 and mat2 shapes cannot be multiplied (1440x128 and 130x64)" when running this below command line: 

`python ./tasks/homo/train_maskDL_long.py --base_dir ./scenes --scene_name statue/images --resize_ratio 8 --gpu_id 0 --alias debug --pose_lr 3e-3  --focal_lr 1e-4 --nerf_lr 3e-4 --fx_only True --num_rows_eval_img 6 --epoch 100 --eval_interval 1`

**Comment by FreeButUselessSoul** [comment] 2023-11-23 01:25
This is due to a mis-use of `occlusion_net` in `eval_one_epoch()`. The problem is now fixed. Sorry for the late reply btw.

**Closed as completed by FreeButUselessSoul** 2023-11-23 01:25 UTC
